### ISSUE TITLE
package removed from CRAN

### ISSUE THREAD

**Issue by toomish** [IMSMWU/RClickhouse#105]
https://cran-archive.r-project.org/web/checks/2024/2024-01-12_check_results_RClickhouse.html

```
Result: WARN
  Found the following significant warnings:
    RcppExports.cpp:46:18: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
    RcppExports.cpp:79:18: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
```

It is already fixed in https://github.com/IMSMWU/RClickhouse/commit/e3edde73ab592bef3dab883969163894a780b574

Please upload new version into CRAN.

**Comment by inkrement** [comment]
@toomish Thank you for reaching out! I just submitted the latest version to cran. It should be available soon.
