### ISSUE TITLE
fail to connect: Operation now in progress

### ISSUE THREAD

**Issue by dvera** [IMSMWU/RClickhouse#107]
Getting error when trying to connect to RClickHouse cloud on AWS. Works fine with curl on the same client:

```
user@host:~$ curl \
--user 'default:PASSWORD'   \
--data-binary 'SELECT 1'   \
https://SUBDOMAIN.REGION.aws.clickhouse.cloud:8443
````
```
1
```

But with RClickhouse on same client:
```
library(RClickhouse)
con <- DBI::dbConnect(RClickhouse::clickhouse(), 
                       host   = "SUBDOMAIN.REGION.aws.clickhouse.cloud",
                       user      = 'default',
                       password      = 'PASSWORD'
 )
```
```
Error in connect(config[["host"]], strtoi(config[["port"]]), config[["db"]],  : 
  fail to connect: Operation now in progress
```

**Comment by inkrement** [comment]
Our client uses the native protocol, not HTTP(s). Consequently, curl is not a proper way to check the connectivity (different ports, different protocols). We might migrate to HTTP(s) in the future (due to convenience), but this is just a plan.

**Comment by karanmehta113** [comment]
@inkrement - apologies, I am new to RClickhouse, and seem to be getting the same error.  If the issue has already been resolved elsewhere, it would be very helpful if you could kindly direct me to the page ?  Below is the code I am using for reference.  Thank you very much in advance for your help.

library(RClickhouse)

db <- 'test'
host_db <- 's3n1gjbm7z.eu-west-2.aws.clickhouse.cloud'
db_port <- 9000
db_user <- 'default'
db_password <-  'YYY'

con <- DBI::dbConnect(RClickhouse::clickhouse(), dbname = db, host=host_db, port=db_port,
                 user=db_user, password=db_password)
                 
Error in connect(config[["host"]], strtoi(config[["port"]]), config[["db"]],  : 
  fail to send data: No error

**Comment by inkrement** [comment]
Have you tried connecting to the same database using the official CLI client and the native protocol? In most cases, it is not the client itself that is the problem, but connectivity issues, which are hard to debug from a distance.
