### ISSUE TITLE
Features & Bugs v0.4

### ISSUE THREAD

**Issue by inkrement** [IMSMWU/RClickhouse#23]
- [x] enhance sql-translation (add custom if null and is null checks; add var and sd functions)
- [x] remove packrat
- [x] uuid support #24 
- [x] search for config file (.e.g, `/etc/RClickhouse.ini`, `~/.R/Clickhouse.ini` or `./RClickhouse.ini`) and load username, hostname, password etc.

**Comment by stiebels** [comment]
last point (config) added recently
