### ISSUE TITLE
dbname parameter not inherited from dbConnect or dbPool

### ISSUE THREAD

**Issue by catlyst** [IMSMWU/RClickhouse#33]
Greetings, I've been using clickhouse-r primarily but was excited to switch over to your package today in order to take advantage of dplyr's interactions with ggplot2. Initial tests performed well but when I tried to switch databases by setting the dbname parameter, calls to tbl() fail because it still thinks the database is "default"

When I try explicitly setting it, e.g. tbl(pool,"dbname.tablename") it reports this error:
 Error in select(conn@ptr, statement) : 
  DB::Exception: Table default.dbname.tablename doesn't exist.

**Comment by stiebels** [comment]
Could you provide a code snippet that makes you error reproducible?

**Comment by vpanfilov** [comment]
@catlyst, you should use `db` angument, not `dbname`.

**N.B.** For setting database name explicitly for single table you can use:
```r
conn %>% dplyr::tbl(dbplyr::in_schema("db_name", "table_name"))
```

**Comment by inkrement** [comment]
@vpanfilov is completely right. The argument is named `db` instead of `dbname`. Seems like `DBI::dbConnect` also uses dbname, so we should add it as alias...

**Comment by catlyst** [comment]
Thanks for the clarification. Keep up the good work, all.
