### ISSUE TITLE
returned Date fields from dbGetQuery not rendering correctly in DT::datatable

### ISSUE THREAD

**Issue by catlyst** [IMSMWU/RClickhouse#34]
Dates do not display correctly (seems like some form of escaping has been applied), and spaces turn into T with a final Z at the end, as shown here:
<img width="275" alt="screen shot 2018-03-23 at 2 12 01 am" src="https://user-images.githubusercontent.com/7286619/37779184-e666b622-2e3f-11e8-8a1f-cde42543a884.png">

However, within R, the data.table object _looks_ fine:
<img width="247" alt="screen shot 2018-03-23 at 2 17 07 am" src="https://user-images.githubusercontent.com/7286619/37779377-5c56e5c8-2e40-11e8-8d0a-95dffacea47b.png">

This DT::datatable problem does not happen when the exact same query is used on clickhouse-r (my only other basis of comparison)

**Comment by vpanfilov** [comment]
@catlyst, this is definately NOT a **RClickhouse** problem. Look [here](https://rstudio.github.io/DT/functions.html) for some info about formatting *DateTime* values in **DT** columns.

**Comment by catlyst** [comment]
Thank you for the link, in addition to a can of "date"d worms, it opened up my appreciation of the POSIXct datatype which is not fully supported in R, but with a combination of [is.POSIXct](https://stackoverflow.com/questions/26412947/reliable-way-to-detect-if-a-column-in-a-data-frame-is-posixct) and adapting code from [here](https://stackoverflow.com/a/37833702/8572007), I managed to get the behaviour I needed.

Thanks again for your good work with Rclickhouse & patience in advising a noob like me.

For posterity (and to save folks in similar predicaments many minutes of googling) here was what worked for my specific purposes of having DT render POSIXct columns within my data.table as 'YYYY-MM-DD hh:mm:ss':

`
is.POSIXct <- function(x) inherits(x, "POSIXct")
is.POSIXlt <- function(x) inherits(x, "POSIXlt")
is.POSIXt <- function(x) inherits(x, "POSIXt")
is.Date <- function(x) inherits(x, "Date")

dt<-data.table(dbGetQuery(pool,sql))
dateCols<-names(Filter(is.POSIXct,dt))
dt<-dt[,(dateCols):=lapply(.SD,as.character), .SDcols=dateCols]
`
