### ISSUE TITLE
request for nullable default columns

### ISSUE THREAD

**Issue by alanpaulkwan** [IMSMWU/RClickhouse#38]
Hi, Clickhouse now supports nullable columns. Is there an elegant way to ask dbWriteTable to make columns nullable by default? If sample data isn't nullable, it's currently an error. This breaks a lot of code. A global option would be excellent.

**Comment by inkrement** [comment]
Good point, we should consider NULLs as default.

**Comment by tridelt** [comment]
The request for this enhancement has been added to #79.
