### ISSUE TITLE
Import data locally

### ISSUE THREAD

**Issue by waynelapierre** [IMSMWU/RClickhouse#41]
Just wondering if you can add data importing function in this package.

**Comment by inkrement** [comment]
Hi @waynelapierre, what do you mean by "data importing function"? A write operation is already supported so you can import data. If you intend to import bigger datasets I would suggest to use the official bash client to get the best performance.

**Comment by waynelapierre** [comment]
I tried this code to import a local CSV data into clickhouse via your package:

```
require(RClickhouse)
require(DBI)
require(tidyverse)

con = dbConnect(clickhouse(),
                host="localhost")

dbWriteTable(con,
             'testing',
             file.choose(), 
             sep=",", 
             row.names=FALSE, 
             header=T, 
             overwrite=T)

tbl(con, "testing") %>% 
  head(3)
```

This code shows nothing and it seems my local CSV file was not successfully imported.

**Comment by inkrement** [comment]
@waynelapierre Although, we provide a method called dbWriteTable, it does not support a direct CSV import. You have to read the data first into a dataframe using read_csv or similar packages. Then you can provide the dataframe to dbWriteTable. More Information about this function can be found right here: https://rdrr.io/cran/DBI/man/dbWriteTable.html. However, keep in mind that this is R's DBI Interface and not RClickhouse (we are just implementing this interface). 

I am closing this issue for now - feel free to reopen it if there is still something unclear.

**Comment by waynelapierre** [comment]
out-of-memory data is the reason i need to use the RClickhouse package. if i can import the data into R, then there is no point of using Clickhouse. are there any other convenient ways of import data to Clickhouse directly?

**Comment by inkrement** [comment]
If you want to import huge data sets, neither RClickhouse nor the other third-party extensions are the right tool for you. To get the best performance, you should always use the command line tool. They wrote it in C++ and it even parallelizes in the last version. We may provide a similar functionality in future. However, it is not the purpose of this package and will never reach the speed of the cli-client.

**Comment by waynelapierre** [comment]
I have looked at the data importing tutorial of clickhouse. The command line part really scared me. Is there any gui through which I can import a local csv data set without having to specify each column's data type? thanks.

**Comment by inkrement** [comment]
How many observations/columns do you have? How big is the data set?

**Comment by waynelapierre** [comment]
My data is about 33.5 gb in size. It has about 30 columns and more than 1 billion rows.

**Comment by inkrement** [comment]
In this case I would still recommend the cli. The usability is "limited", however, it's not too complicated and really fast. All UIs I know are not directly streaming it to the db, but loading it in the memory first. Therefore, you should give the cli a try.
