### ISSUE TITLE
dplyr JOINs in ClickHouse version 18.10.3

### ISSUE THREAD

**Issue by oflasch** [IMSMWU/RClickhouse#44]
When trying a dyplr `left_join()`, RClickhouse emits the standard SQL join syntax, including table prefixes, which are not supported in Clickhouse (I'm using ClickHouse server version 18.10.3 revision 54405).

There has been custom code for joins in dplyr.R (see #14), but this has since been removed?

Do I overlook something or are joins unsupported at the moment?

Many thanks in advance for your help in this matter.

**Comment by inkrement** [comment]
Hi Oliver,

We had basic support for joins, but clickhouse used a special (non-standard conform) syntax. Furthermore, they announced to change it in the new feature and provide also support for ON clauses. I haven't checked the status quo for some months now, but we wanted to wait for those changes. Of course we want to provide as most (common) functionality as possible, but in this case we wanted to wait for bigger changes. 

Thanks for your pull request, we'll take a look at it.

cheers

**Comment by oflasch** [comment]
Many thanks for your quick reply! ClickHouse now supports ON-clauses, but joins are still non-standard in other ways. If I understand the roadmap correctly, joins are still subject to changes/improvements. So it might make sense to wait for the syntax to stabilize. We have a working dplyr-join implementation in the master branch of our sourcewerk fork of your driver, if you want to integrate it to the join fork.

**Comment by inkrement** [comment]
merged now. Thanks for your contribution!
