### ISSUE TITLE
investigate overhead caused by RClickhouse

### ISSUE THREAD

**Issue by jangorecki** [IMSMWU/RClickhouse#47]
Clickhouse is meant to be low-latency query engine. Thus it would be useful to measure overhead related to different layers applied by the package. Measure speed of cli vs. DBI vs. RClickhouse.

**Comment by inkrement** [comment]
Although, we might provide something like this is future, I am afraid to say that it does not have any priority at all. You are right, Clickhouse tries to be as performant as possible. However, the R interface is created in first place for exploratory data science and not for real time applications. Therefore, we intend to provide a nice/stable interface and add more and more features/extend usability over time. 

Speed is important, but it is not our (current) focus.
