### ISSUE TITLE
install error for 'BigInt.hpp'

### ISSUE THREAD

**Issue by sean0310** [IMSMWU/RClickhouse#53]
Hi..
I use devtools to install RClickhouse and have an error message during installation.

`
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I. -I../inst/include -I./vendor/clickhouse-cpp -I./vendor/clickhouse-cpp/contrib -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o

In file included from ./vendor/clickhouse-cpp/clickhouse/columns/column.h:5:0,
                 from ./vendor/clickhouse-cpp/clickhouse/block.h:3,
                 from ./vendor/clickhouse-cpp/clickhouse/query.h:3,
                 from ./vendor/clickhouse-cpp/clickhouse/client.h:3,
                 from ../inst/include/RClickhouse.h:4,
                 from RcppExports.cpp:4:

./vendor/clickhouse-cpp/clickhouse/columns/../types/types.h:3:10: fatal error: BigInt.hpp: No such file or directory

 #include <BigInt.hpp>
          ^~~~~~~~~~~~
compilation terminated.
/usr/lib/R/etc/Makeconf:177: recipe for target 'RcppExports.o' failed
make: *** [RcppExports.o] Error 1

ERROR: compilation failed for package ‘RClickhouse’`

Does there have any suggestion for this? thanks to all...^^

**Comment by danielw2904** [comment]
Compile error is fixed at least under linux. The existing windows compilation bug seems to persist (tested with r-hub). This should be tested however. Please submit a new issue if there are any problems.
