### ISSUE TITLE
Version 0.5.1 doesn't work on Windows

### ISSUE THREAD

**Issue by vpanfilov** [IMSMWU/RClickhouse#56]
Hello.

Thanks for the long-anticipated update of your package, but I can't get it working on Windows:

The following code is working fine on Linux with RClickhouse 0.5.1:
```r
conn <- DBI::dbConnect(RClickhouse::clickhouse(), host = "10.0.0.219")
```
but on Windows I get:
```
Error in connect(config[["host"]], strtoi(config[["port"]]), config[["db"]],  :
  fail to connect: No error
```

**Comment by inkrement** [comment]
Thank you for this bug report! We'll take a look at it and get back to you asap.

**Comment by danielw2904** [comment]
See also 0bc128028d8a03288e117bd0353c4bdc0d343429

**Comment by vpanfilov** [comment]
@danielw2904 Thanks for the fix, connecting on Windows is working now.
