### ISSUE TITLE
'con' must not be NULL error in dplyr join

### ISSUE THREAD

**Issue by isanakamishiro** [IMSMWU/RClickhouse#57]
Hello, and great thanks to provide nice package.

When I use dplyr::XXX_join, I got the following error.

`Error: con must not be NULL`

Probably 'sql_vector' needs to set "con" parameter in line.193 in 'R/dplyr.R'.
`on <- sql_vector(paste0(sql_escape_ident(con, by$x), " = ", sql_escape_ident(con, by$y)), collapse = " AND ", parens = TRUE)`

It seems to be need to append `con = con`.

**Comment by tridelt** [comment]
Thank you @isanakamishiro
Greatly appreciated the report. We hope that fixed it.
