### ISSUE TITLE
Join on the same key is not possible

### ISSUE THREAD

**Issue by vrkrv** [IMSMWU/RClickhouse#61]
Hi!

I use pkg v0.5.2. When I join tables on the same key it results in error:
```r
db1 %>%
  select(a1, a2) %>%
  left_join(db2 %>% select(a1, b1, by = c("a1"))
# Error in select(conn@ptr, statement) : 
#  DB::Exception: Column 'a1' is ambiguous
``` 

If I run the same statement with explain:
```r
db1 %>%
  select(a1, a2) %>%
  left_join(db2 %>% select(a1, b1, by = c("a1")) %>%
  explain
# <SQL>
# SELECT `a1`, `a2`, `b1`
# FROM db1 
#   ALL LEFT JOIN (SELECT `a1`, `b1`
# FROM `tmp_newgroup`) 
#   ON (`a1` = `a1`)
# <PLAN>
``` 
I can join two DBs if I rename key in one of them and provide explicit by statement.
The cause of the problem is clear -- sql translator do not name left/right tables.
In sql correct statment shall look like this:
```sql
SELECT A.`a1`, A.`a2`, B.`b1`
FROM db1 A
  ALL LEFT JOIN (SELECT `a1`, `b1`
FROM `tmp_newgroup`) B 
  ON (A.`a1` = B.`a1`)
```

**Comment by tridelt** [comment]
Thank you very much for creating the issue. We will try to fix it as quickly as possible.

**Comment by tridelt** [comment]
Hello :)
it looks like a prior modification that was added to address Issue #44 was responsible. Since then multiple updates have been made. For now, I made some changes. I will continue with testing and see if this resolved the issue entirely and also doesn't break anything form #44
