### ISSUE TITLE
I met "Error in connect(config[["host"]], strtoi(config[["port"]]), config[["db"]],  :    closed: No error" when connect CK with  RClickhouse

### ISSUE THREAD

**Issue by huangxp12** [IMSMWU/RClickhouse#62]
con <- dbConnect(RClickhouse::clickhouse(), user  = '*********',password ='********', host="r***nt-ck.b***zhan.com",port=80,dbname='min***k')

Error in connect(config[["host"]], strtoi(config[["port"]]), config[["db"]],  : 
  closed: No error

When I reuse con ,I get "couldn't find the object "con""
> con
错误: 找不到对象'con'

**Comment by tridelt** [comment]
Hello!
may I ask what operating system you are using? Also with which version of RClickHouse did you experience the error?Compatibility issues with Windows have previously been resolved with e8d9439.

**Comment by tridelt** [comment]
Due to inactivity, I close this issue for now. If this problem should become relevant again to you but please feel free to leave a comment.
