### ISSUE TITLE
Decimal support

### ISSUE THREAD

**Issue by l4l** [IMSMWU/RClickhouse#63]
Selecting a decimal row leads to an error: `Error in fetch(res@ptr, n) : cannot read unsupported type: Decimal(18,9)`

**Comment by tridelt** [comment]
Thank you very much for raising an issue. We will investigate.

**Comment by feilx** [comment]
@tridelt Has the problem been solved?

**Comment by tridelt** [comment]
The request for this datatype has been added to #79 as part of adding support for more datatypes.
