### ISSUE TITLE
Naming convention for name of database

### ISSUE THREAD

**Issue by jakejh** [IMSMWU/RClickhouse#69]
In most of the other DBI-compliant interfaces I'm aware of, the name of the database is specified by an argument called `dbname`, not `db`. See [RPostgres](https://rpostgres.r-dbi.org/reference/dbconnect-pqdriver-method), [RMariaDB](https://rmariadb.r-dbi.org/reference/dbconnect-mariadbdriver-method), and [RSQLite](https://rsqlite.r-dbi.org/reference/sqlite). Would you consider following this convention? Thanks for making this package available to the community.

https://github.com/IMSMWU/RClickhouse/blob/65c04ff0b09e3c0b56875997e8a9e31a00becde5/R/ClickhouseDriver.R#L145

**Comment by danielw2904** [comment]
For me this would be fine. I'll prepare a PR

**Comment by jakejh** [comment]
Thanks!

**Comment by inkrement** [comment]
should be resolved now.
