### ISSUE TITLE
Add methods for dbCreateTable and dbAppendTable

### ISSUE THREAD

**Issue by jakejh** [IMSMWU/RClickhouse#71]
I know it's possible to use `dbWriteTable` with arguments `overwrite` or `append`, but the [current DBI documentation](https://dbi.r-dbi.org/reference/dbwritetable) suggests using `dbCreateTable` and `dbAppendTable`. Having these methods would help me avoid using different code for different DBMSs.

**Comment by inkrement** [comment]
We'll put it on the TODO-List, but feel free to provide a pull request.

**Comment by jakejh** [comment]
Ok, thanks. We'll see if we can make a PR.

**Comment by JSchoenbachler** [comment]
We are working on a PR for this functionality, however we don't want this to be implemented in a way that goes against the structure of other code in the repo. Which way would you prefer:

1. Create dbCreateTable and dbAppendTable methods, where much of dbCreateTable/dbAppendTable gets lifted from the current dbWriteTable, and then revise dbWriteTable to call dbCreateTable or dbAppendTable.
2. Create dbCreateTable and dbAppendTable methods that just call dbWriteTable with particular values of arguments.

**Comment by tridelt** [comment]
Hi @JSchoenbachler and @jakejh

I think Option 2 might be the better choice. Notwithstanding, I think we should utilise code from dbWriteTable() which already works reliably.

I have taken the liberty and started working on a dbCreateTable(). Please feel free to comment and add changes. If you would like to, you can also write a test-case in the file tests/testthat/test-testdriven_development.R which details your specific needs. There, I have prepared a template for your issue #71. That way we get a concrete idea of what users of RClickhouse require.

Yours,
Tridelt

**Comment by JSchoenbachler** [comment]
Sounds good, I'm going to work on a dbAppendTable function and a pull request for that. I'll use the same structure as your dbCreateTable function as a model so that it's consistent.

**Comment by tridelt** [comment]
merged! thank you very much for your commits
