### ISSUE TITLE
Http port connect support

### ISSUE THREAD

**Issue by xwydq** [IMSMWU/RClickhouse#78]
for some reasons, external accessible port only support http port (8123)，is there any ways to use http port create connect

**Comment by tridelt** [comment]
This package currently only supports the binary protocol on port 8123. If you must use http protocol for Clickhouse, clickhouse also has an [official http-interface](https://clickhouse.tech/docs/en/interfaces/http/) which can be accessed by, among many others, a graphical web interface named [tabix](https://tabix.io/).
