### ISSUE TITLE
TimeZone problems

### ISSUE THREAD

**Issue by avraam-inside** [IMSMWU/RClickhouse#81]
The code I run in R (via RClickhouse) and the result (wrong, timezone left +3 hours)
![image](https://user-images.githubusercontent.com/52919010/112392864-2f245900-8d0b-11eb-87af-2bca097598cd.png)|

The same code that I run in Tabix and the result (correct, timezone left +0 hours)
![image](https://user-images.githubusercontent.com/52919010/112393256-d7d2b880-8d0b-11eb-8435-00758b1af356.png)

What is it? Why? Obviously, this is not a ClickHouse issue, but a JDBC driver issue.

UPD: Together with @tridelt in the correspondence below, we found out that there is a problem, but it is not in JDBC, because Clickhouse driver does not use it

**Comment by tridelt** [comment]
Hi @avraam-1997 ,
thanks for raising an issue. I don't understand why this would be a JDBC driver issue.
Would you be so kind and elaborate?
Yours
Tridelt

**Comment by avraam-1997** [comment]
Hi, thank you for your prompt response)

Of course I will explain

I use the same code in DBeaver and get the same error:
![image](https://user-images.githubusercontent.com/52919010/112393923-e5d50900-8d0c-11eb-8fc1-60797ba34089.png)

RClickHouse and DBeaver combine only 1 element - both go through the JDBC driver, while Tabix uses HTTP

At the same time, the function works correctly via HTTP.

At a minimum, the function has a "timezone" parameter and the data changes exactly in Tabix when it is used, while in R or DBeaver there is no reaction

Additional example with 'Asia/Yekaterinburg': 
![image](https://user-images.githubusercontent.com/52919010/112394317-8fb49580-8d0d-11eb-9795-1a2981089eb4.png)
and 
![image](https://user-images.githubusercontent.com/52919010/112394382-ae1a9100-8d0d-11eb-8115-0a9e47111b69.png)

**Comment by tridelt** [comment]
Hi @avraam-1997 ,
I appreciate the effort to help find the root of the issue, but RClickhouse doesn't rely on Java Database Connectivity (JDBC). No java here.
Yours
Tridelt

**Comment by avraam-1997** [comment]
Hi @tridelt 
Okay, so RClickHouse doesn't use Java. You should know better) 

But what is interesting, it is similar with problems in JDBC (DBeaver exactly uses JDBC)

And the problem with timezones still exists in RClickHouse

**Comment by tridelt** [comment]
Hi @avraam-1997 
regardless, thanks for taking the time to open an issue here.
May I ask if you have you also opened an issue for this problem at [dbeaver](https://github.com/dbeaver/dbeaver)? If yes, would you mind linking it here?
Yours
Luca

**Comment by avraam-1997** [comment]
Hi @tridelt 

Created a request in the JDBC driver under DBeaver: https://github.com/ClickHouse/clickhouse-jdbc/issues/604

I don't know how to link it, this is the first time I've raised the issue on github(

And thank you for your time!

**Comment by tridelt** [comment]
Thanks! 😃
