### ISSUE TITLE
Error: cannot write unsupported type: Void - DateTime64(3)

### ISSUE THREAD

**Issue by avraam-inside** [IMSMWU/RClickhouse#84]
Hey!

Created a table in ClickHouse with 1 columns of type DateTime64(3)

```sql
CREATE OR REPLACE TABLE TEST.TEST 
(
timestamp DateTime64(3)
)
ENGINE = MergeTree
PARTITION BY tuple()
ORDER BY tuple()
SETTINGS index_granularity = 8192 
```

Created 2 different data.table:

```r
dt_test <- 
  data.table(
    timestamp = anytime::anytime(1626266518.551)
  )

dt_test <- 
  data.table(
    timestamp = 1626266518.551
  )
```

I am trying to make an insert in the database of these two options - an error is returned: 
`Error in insert (conn@ptr, qname, value):
   cannot write unsupported type: Void`

**Comment by inkrement** [comment]
DateTime64 is a rather new data type, which we do not support yet. @tridelt could you check if the clickhouse-cpp version in use already supports this type? If so it should be trivial to add.

**Comment by den-crane** [comment]
DateTime64 is supported by  clickhouse-cpp

**Comment by tridelt** [comment]
RClickhouse uses an older clickhouse-cpp which doesn't support DateTime64. In the future should we upgrade to a more current clickhouse-cpp version, we will definitely consider adding support.
