### ISSUE TITLE
insert into values not work

### ISSUE THREAD

**Issue by xwydq** [IMSMWU/RClickhouse#86]
```
conn_ck <- DBI::dbConnect(
  RClickhouse::clickhouse(), 
  db = "test",
  host = "localhost",
  port = 9000,
  username = "default",
  password = "test"
)

dbSendQuery(conn_ck, "INSERT INTO test.a (op) VALUES ('aaa');")
dbSendStatement(conn_ck, "INSERT INTO test.a (op) VALUES ('aaa');")
```

dbSendQuery; dbSendStatement not work for insert into special value

**Comment by tridelt** [comment]
hi @xwydq,
thanks for opening an issue.
Your snippet is not supported by this RClickhouse client, see #60.
Instead, try inserting you data with `dbWriteTable` in append-mode or `dbAppendTable`.
Yours
Tridelt : )
