### ISSUE TITLE
Tables with datetime columns designated as Nullable() prompt error upon appending

### ISSUE THREAD

**Issue by zylsun** [IMSMWU/RClickhouse#91]
This bug is previously mentioned here: https://github.com/IMSMWU/RClickhouse/issues/75#issuecomment-951649715.  I raise it again in case of omission.

I made the following changes in my personal repo for more than 4 months, and everything is fine since then.  I am not familiar with the github or the automatic testing process so I have to leave the formal fix to you.  

``` CPP
// line#366
// the master branch now
      return vecToScalar<ColumnDateTime, const std::time_t>(v);

// what I changed
      return vecToScalar<ColumnDateTime, const std::time_t>(v, nullCol);
```

Wish to see it fixed soon.

**Comment by tridelt** [comment]
Hi @zylsun,
thank you very much for raising this issue. The same Bug which occurred for ColumnDate and was fixed in c2952bf33151a07c0b154f460f3627d621b0956b  also occurs with ColumnDateTime. 
b49a033480a165edc3d324aa72905437b4f73d61 is the fix for this issue.
Thanks!
