### ISSUE TITLE
Loading a Bool-datatype column (reopened)

### ISSUE THREAD

**Issue by avraam-inside** [IMSMWU/RClickhouse#95]
Bool-datatype is exists in clickhouse: https://clickhouse.com/docs/en/sql-reference/data-types/boolean

Please register the Bool-datatype when loading the dataset in the form of logical-class. 

 P.S.: reopened version of closed issue https://github.com/IMSMWU/RClickhouse/issues/94 by @inkrement who closed it referring to incorrect documentation and did not return to open it.

**Comment by inkrement** [comment]
See other (linked) issue; Project is maintained by volunteers in their spare time and, therefore, responses may take time. This is not an excuse, but how it is.
